### ISSUE TITLE
Entering Input Filenames is time consuming

### ISSUE THREAD

**Issue by andystallwood** [andystallwood/CiscoScripts#13]
Request a folder name for both input files and the log file directory and then ask for the hosts file name , command file and log directory

**Comment by billybutler** [comment]
Can files be assumes as a default and you can over type of you want?

hostfile 'hostfile.csv' unless you type something else?
command file 'Command.csv' unless you type something else?
log directory '\log' unless you type something else?

**Comment by andystallwood** [comment]
Good shout, I'll try to do that.
