### ISSUE TITLE
Please can the log file name be changed to IP-Date-time. 

### ISSUE THREAD

**Issue by billybutler** [andystallwood/CiscoScripts#19]
The filename at present is date/time/ip which is not simple to search for IP address. the filename being the other way allows for you to find the host quickly from the error files. Thanks.

**Comment by billybutler** [comment]
I am happy to have a go at this change and submit for your review

**Comment by andystallwood** [comment]
Go for it mate. Either just make a change to the file directly, or even better, go into the file, create a new branch (call it something that describes what you are doing) and then make your commit there. I will then check and merge that branch back into the master branch.
